---
- hosts: all
  become: true
  vars:
    - audit_logs:
        - '/var/log/audit/audit.log'
        - '/var/log/wtmp'
        - '/var/log/lastlog'
  tasks:
    - name: updating apt-cache
      apt:
        update_cache: true
      when: >
            ansible_distribution == "Ubuntu" and
            repo_added.changed

    - name: Preparing and installing Hyper-V kernel packages
      apt:
        name: "linux-virtual"
        state: present
      when: ansible_os_family == "Debian"

    - name: Installing Hyper-V tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - 'linux-tools-virtual'
        - 'linux-cloud-tools-virtual'
      when: ansible_os_family == "Debian"
      
    - name: stopping rsyslog service
      service:
        name: "rsyslog"
        state: stopped
      when: ansible_os_family == "Debian"

    - name: clearing audit logs
      file:
        path: "{{ item }}"
        state: absent
      with_items: audit_logs

    - name: cleaning up udev rules
      file:
        path: "/etc/udev/rules.d/70-persistent-net.rules"
        state: absent

    - name: cleaning up tmp directories
      command: "rm -rf {{ item }}"
      with_items:
        - '/tmp/*'
        - '/var/tmp/*'

    - name: cleaning up ssh keys
      command: "rm -f /etc/ssh/ssh_host_*"
